# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QVBoxLayout, QWidget
from pyqtlet import L, MapWidget
from PyQt5.QtCore import *
import sys
import ThreadEngine
import data

class TTT(QThread):

    progress_update = pyqtSignal(int)

    def __init__(self, ui):
        super(TTT, self).__init__()
        self.ui = ui

    def run(self):
        _translate = QtCore.QCoreApplication.translate
        ThreadEngine.go(self.ui, _translate, self.progress_update)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 575)
        MainWindow.setStyleSheet("background-color : rgb(85, 87, 83)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 291, 391))
        self.frame.setStyleSheet("background-color:rgb(46, 52, 54);\n"
"border-radius:5px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(200, 140, 71, 81))
        self.label_9.setStyleSheet("color : rgb(238, 238, 236)")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 71, 81))
        self.label_4.setStyleSheet("color : rgb(238, 238, 236)")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(110, 220, 71, 81))
        self.label_10.setStyleSheet("color : rgb(238, 238, 236)")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.txtSensorKanan = QtWidgets.QLabel(self.frame)
        self.txtSensorKanan.setGeometry(QtCore.QRect(200, 170, 74, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtSensorKanan.setFont(font)
        self.txtSensorKanan.setStyleSheet("color : rgb(238, 238, 236);\n"
"background-color: rgba(0,0,0,0%)")
        self.txtSensorKanan.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSensorKanan.setObjectName("txtSensorKanan")
        self.txtSensorKiri = QtWidgets.QLabel(self.frame)
        self.txtSensorKiri.setGeometry(QtCore.QRect(20, 170, 74, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtSensorKiri.setFont(font)
        self.txtSensorKiri.setStyleSheet("color : rgb(238, 238, 236);\n"
"background-color: rgba(0,0,0,0%)")
        self.txtSensorKiri.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSensorKiri.setObjectName("txtSensorKiri")
        self.txtSensorBelakang = QtWidgets.QLabel(self.frame)
        self.txtSensorBelakang.setGeometry(QtCore.QRect(110, 250, 74, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtSensorBelakang.setFont(font)
        self.txtSensorBelakang.setStyleSheet("color : rgb(238, 238, 236);\n"
"background-color: rgba(0,0,0,0%)")
        self.txtSensorBelakang.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSensorBelakang.setObjectName("txtSensorBelakang")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 50, 71, 81))
        self.label.setStyleSheet("color : rgb(238, 238, 236)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.txtSensorDepanKiri = QtWidgets.QLabel(self.frame)
        self.txtSensorDepanKiri.setGeometry(QtCore.QRect(20, 80, 71, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(True)
        self.txtSensorDepanKiri.setFont(font)
        self.txtSensorDepanKiri.setAutoFillBackground(False)
        self.txtSensorDepanKiri.setStyleSheet("color : rgb(238, 238, 236);\n"
"background-color: rgba(0,0,0,0%)")
        self.txtSensorDepanKiri.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSensorDepanKiri.setObjectName("txtSensorDepanKiri")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(200, 50, 71, 81))
        self.label_8.setStyleSheet("color : rgb(238, 238, 236)")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.txtSensorDepanKanan = QtWidgets.QLabel(self.frame)
        self.txtSensorDepanKanan.setGeometry(QtCore.QRect(200, 80, 74, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtSensorDepanKanan.setFont(font)
        self.txtSensorDepanKanan.setStyleSheet("color : rgb(238, 238, 236);\n"
"background-color: rgba(0,0,0,0%)")
        self.txtSensorDepanKanan.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSensorDepanKanan.setObjectName("txtSensorDepanKanan")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(110, 40, 71, 81))
        self.label_7.setStyleSheet("color : rgb(238, 238, 236)")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.txtSensorDepan = QtWidgets.QLabel(self.frame)
        self.txtSensorDepan.setGeometry(QtCore.QRect(110, 70, 74, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtSensorDepan.setFont(font)
        self.txtSensorDepan.setStyleSheet("color : rgb(238, 238, 236);\n"
"background-color: rgba(0,0,0,0%);")
        self.txtSensorDepan.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSensorDepan.setObjectName("txtSensorDepan")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color : rgb(238, 238, 236);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(20, 320, 251, 51))
        self.line.setStyleSheet("background-color:rgb(85, 87, 83)")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.txtSensorActionMessage = QtWidgets.QLabel(self.frame)
        self.txtSensorActionMessage.setGeometry(QtCore.QRect(30, 330, 231, 31))
        self.txtSensorActionMessage.setStyleSheet("color:rgb(238, 238, 236);\n"
"background-color: rgba(0,0,0,0%);")
        self.txtSensorActionMessage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtSensorActionMessage.setObjectName("txtSensorActionMessage")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(320, 20, 541, 531))
        self.frame_2.setStyleSheet("background-color:rgb(46, 52, 54);\n"
"border-radius:5px\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color : rgb(238, 238, 236);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(40, 20, 118, 3))
        self.line_2.setStyleSheet("background-color:rgb(238, 238, 236)")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame_2)
        self.line_3.setGeometry(QtCore.QRect(380, 20, 118, 3))
        self.line_3.setStyleSheet("background-color:rgb(238, 238, 236)")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 501, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)

        # 
        self.mapWidget = MapWidget()
        self.verticalLayout.addWidget(self.mapWidget)

        # Working with the maps with pyqtlet
        self.map = L.map(self.mapWidget)
        self.map.setView(data.coordinates[0], 20)
        L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png').addTo(self.map)
        self.marker = L.marker(data.coordinates[0])
        self.marker.addTo(self.map)
        L.polyline(data.coordinates, {'color':'blue'}).addTo(self.map)
        # Working with the maps with pyqtlet

        self.label_5.setGeometry(QtCore.QRect(20, 430, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color : rgb(238, 238, 236);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(20, 460, 161, 41))
        self.frame_3.setStyleSheet("background-color:rgb(40, 40, 40)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.txtMileage = QtWidgets.QLabel(self.frame_3)
        self.txtMileage.setGeometry(QtCore.QRect(0, 10, 161, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(18)
        self.txtMileage.setFont(font)
        self.txtMileage.setStyleSheet("color:rgb(238, 238, 236)")
        self.txtMileage.setAlignment(QtCore.Qt.AlignCenter)
        self.txtMileage.setObjectName("txtMileage")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(200, 430, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color : rgb(238, 238, 236);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(200, 460, 321, 41))
        self.frame_4.setStyleSheet("background-color:rgb(40, 40, 40)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.energyBar = QtWidgets.QProgressBar(self.frame_4)
        self.energyBar.setGeometry(QtCore.QRect(10, 10, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.energyBar.setFont(font)
        self.energyBar.setStyleSheet("color:rgb(238, 238, 236)")
        self.energyBar.setMaximum(3000)
        self.energyBar.setProperty("value", 3000)
        self.energyBar.setAlignment(QtCore.Qt.AlignCenter)
        self.energyBar.setObjectName("energyBar")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(870, 20, 331, 221))
        self.frame_5.setStyleSheet("background-color:rgb(46, 52, 54);\n"
"border-radius:5px\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.txtSpeedometer = QtWidgets.QLabel(self.frame_5)
        self.txtSpeedometer.setGeometry(QtCore.QRect(70, 30, 181, 151))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(80)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.txtSpeedometer.setFont(font)
        self.txtSpeedometer.setStyleSheet("color:rgb(238, 238, 236)")
        self.txtSpeedometer.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSpeedometer.setObjectName("txtSpeedometer")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(130, 180, 71, 21))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(238, 238, 236)")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color : rgb(238, 238, 236);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(20, 420, 291, 131))
        self.frame_7.setStyleSheet("background-color:rgb(46, 52, 54);\n"
"border-radius:5px\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_20 = QtWidgets.QLabel(self.frame_7)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color : rgb(238, 238, 236);")
        self.label_20.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.txtLatitude = QtWidgets.QLabel(self.frame_7)
        self.txtLatitude.setGeometry(QtCore.QRect(10, 40, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtLatitude.setFont(font)
        self.txtLatitude.setStyleSheet("color : rgb(238, 238, 236);")
        self.txtLatitude.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.txtLatitude.setObjectName("txtLatitude")
        self.txtLongitude = QtWidgets.QLabel(self.frame_7)
        self.txtLongitude.setGeometry(QtCore.QRect(10, 90, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtLongitude.setFont(font)
        self.txtLongitude.setStyleSheet("color : rgb(238, 238, 236);")
        self.txtLongitude.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.txtLongitude.setObjectName("txtLongitude")
        self.label_23 = QtWidgets.QLabel(self.frame_7)
        self.label_23.setGeometry(QtCore.QRect(10, 70, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color : rgb(238, 238, 236);")
        self.label_23.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(870, 510, 331, 41))
        self.frame_8.setStyleSheet("background-color:rgb(46, 52, 54);\n"
"border-radius:5px\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_21 = QtWidgets.QLabel(self.frame_8)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color : rgb(238, 238, 236);")
        self.label_21.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(870, 430, 331, 71))
        self.frame_9.setStyleSheet("background-color:rgb(46, 52, 54);\n"
"border-radius:5px\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.txtTotalDistance = QtWidgets.QLabel(self.frame_9)
        self.txtTotalDistance.setGeometry(QtCore.QRect(210, 10, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txtTotalDistance.setFont(font)
        self.txtTotalDistance.setStyleSheet("color : rgb(238, 238, 236);")
        self.txtTotalDistance.setAlignment(QtCore.Qt.AlignCenter)
        self.txtTotalDistance.setObjectName("txtTotalDistance")
        self.label_14 = QtWidgets.QLabel(self.frame_9)
        self.label_14.setGeometry(QtCore.QRect(20, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color : rgb(238, 238, 236);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        self.frame_11.setGeometry(QtCore.QRect(870, 250, 331, 171))
        self.frame_11.setStyleSheet("background-color:rgb(46, 52, 54);\n"
"border-radius:5px\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_19 = QtWidgets.QLabel(self.frame_11)
        self.label_19.setGeometry(QtCore.QRect(30, 100, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color : rgb(238, 238, 236);")
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.txtTotalDistance_3 = QtWidgets.QLabel(self.frame_11)
        self.txtTotalDistance_3.setGeometry(QtCore.QRect(30, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txtTotalDistance_3.setFont(font)
        self.txtTotalDistance_3.setStyleSheet("color : rgb(238, 238, 236);")
        self.txtTotalDistance_3.setAlignment(QtCore.Qt.AlignCenter)
        self.txtTotalDistance_3.setObjectName("txtTotalDistance_3")
        self.label_16 = QtWidgets.QLabel(self.frame_11)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color : rgb(238, 238, 236);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_11)
        self.label_17.setGeometry(QtCore.QRect(150, 20, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color : rgb(238, 238, 236);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.txtTotalDistance_4 = QtWidgets.QLabel(self.frame_11)
        self.txtTotalDistance_4.setGeometry(QtCore.QRect(170, 40, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txtTotalDistance_4.setFont(font)
        self.txtTotalDistance_4.setStyleSheet("color : rgb(238, 238, 236);")
        self.txtTotalDistance_4.setAlignment(QtCore.Qt.AlignCenter)
        self.txtTotalDistance_4.setObjectName("txtTotalDistance_4")
        self.label_24 = QtWidgets.QLabel(self.frame_11)
        self.label_24.setGeometry(QtCore.QRect(30, 120, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color : rgb(238, 238, 236);")
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.t = TTT(self)
        self.t.start()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dashboard Smart Car"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/circle.png\" width=\"70\"/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/circle.png\" width=\"70\"/></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/circle.png\" width=\"70\"/></p></body></html>"))
        self.txtSensorKanan.setText(_translate("MainWindow", "0"))
        self.txtSensorKiri.setText(_translate("MainWindow", "0"))
        self.txtSensorBelakang.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/circle.png\" width=\"70\"/></p></body></html>"))
        self.txtSensorDepanKiri.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/circle.png\" width=\"70\"/></p></body></html>"))
        self.txtSensorDepanKanan.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/circle.png\" width=\"70\"/></p></body></html>"))
        self.txtSensorDepan.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "SENSORS PANEL"))
        self.txtSensorActionMessage.setText(_translate("MainWindow", "......"))
        self.label_3.setText(_translate("MainWindow", "MAIN PANEL"))
        self.label_5.setText(_translate("MainWindow", "MILEAGE IN METER"))
        self.txtMileage.setText(_translate("MainWindow", "0000000000"))
        self.label_11.setText(_translate("MainWindow", "ENERGY"))
        self.txtSpeedometer.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "km/h"))
        self.label_13.setText(_translate("MainWindow", "SPEEDOMETER"))
        self.label_20.setText(_translate("MainWindow", "Latitude"))
        self.txtLatitude.setText(_translate("MainWindow", "0.000000000"))
        self.txtLongitude.setText(_translate("MainWindow", "0.000000000"))
        self.label_23.setText(_translate("MainWindow", "Longitude"))
        self.label_21.setText(_translate("MainWindow", "Created by Jeffry Suyanto"))
        self.txtTotalDistance.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "TOTAL DISTANCE"))
        self.label_19.setText(_translate("MainWindow", "MUSIC"))
        self.txtTotalDistance_3.setText(_translate("MainWindow", "20 C"))
        self.label_16.setText(_translate("MainWindow", "AC TEMP"))
        self.label_17.setText(_translate("MainWindow", "ENGINE TEMP"))
        self.txtTotalDistance_4.setText(_translate("MainWindow", "85 C"))
        self.label_24.setText(_translate("MainWindow", "Habib Syech - Turi putih"))

import circle_rc

if __name__ == '__main__':
        app = QtWidgets.QApplication(sys.argv)
        dashboard = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(dashboard)
        dashboard.show()
        app.exec_()